M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, June 11, 2023 at 02:42:47 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-11T14:42:47-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1772
%
G90
G05
T1
X5.1608Y-4.3198
T2
X3.0545Y-3.7391
X7.6995Y-3.7391
T3
X4.1568Y-3.4438
X6.5972Y-3.4438
T0
M30
