M48
; DRILL file {KiCad 7.0.9} date Wednesday, December 20, 2023 at 05:33:42 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-20T17:33:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X5.9409Y-4.126
X5.9429Y-4.5374
T2
X5.7677Y-4.7126
X5.8234Y-4.7683
T3
X5.5472Y-4.4488
X5.6555Y-4.5669
T0
M30
